#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Judge2: LLM-as-a-judge for detecting genuine human–LLM system interaction studies.

Goal:
- Only re-judge rows where LLM_Decision != "exclude"
- Add three new columns:
    Judge2_include
    Judge2_confidence
    Judge2_reason

Inclusion rule:
- INCLUDE only if human participants directly interact with an LLM system during the study
  (e.g. chatting, prompting, iterating, receiving model responses in-session, using an
  LLM-powered interface with a live interaction loop).

Exclusion rule:
- EXCLUDE if humans only annotate/rate/rank/review LLM outputs, or compare static outputs,
  without directly interacting with the LLM system.
- EXCLUDE if there is no human user study involving LLM interaction.

Unknown:
- UNKNOWN if the PDF does not provide enough evidence.

Input CSV expected columns:
Venue, Year, Title, Abstract, URL, LLM_Decision, Confidence, Judge_Include, Judge_Confidence, Judge_Reason, ...

Output:
- New CSV with Judge2_include, Judge2_confidence, Judge2_reason
- Resumable JSONL log

Notes:
- Requires PDFs already downloaded in PDF_DIR.
- Reads API key from environment variable OPENAI_API_KEY
"""

import os
import re
import json
import time
import hashlib
from typing import Dict, Tuple

import pandas as pd
from tqdm import tqdm
from openai import OpenAI


# ===================== CONFIG =====================
INPUT_CSV = "/scratch/nicole/human_subject/output/papers_llm_judged.csv"
OUTPUT_CSV = "/scratch/nicole/human_subject/output/papers_llm_judge2.csv"
PDF_DIR = "/scratch/nicole/human_subject/pdfs"
LOG_JSONL = "/scratch/nicole/human_subject/output/judge2_log.jsonl"

DECISION_COL = "LLM_Decision"
URL_COL = "URL"
VENUE_COL = "Venue"
YEAR_COL = "Year"
TITLE_COL = "Title"

SAVE_EVERY = 10
MAX_OUTPUT_TOKENS = 500

# Suggested stronger document judge than your original gpt-4o-mini
MODEL = "gpt-4.1-mini"
# ================================================


def norm(s: str) -> str:
    return re.sub(r"\s+", " ", str(s or "")).strip()


def sha1_short(s: str, n: int = 10) -> str:
    return hashlib.sha1(s.encode("utf-8", errors="ignore")).hexdigest()[:n]


def safe_filename(s: str, max_len: int = 120) -> str:
    s = norm(s)
    s = re.sub(r"[^\w\-\.\(\)\[\] ]+", "_", s)
    s = re.sub(r"\s+", " ", s).strip().replace(" ", "_")
    if len(s) > max_len:
        s = s[:max_len]
    return s or "paper"


def build_expected_pdf_path(row: dict) -> str:
    venue = safe_filename(str(row.get(VENUE_COL, "") or "VENUE"))
    year = safe_filename(str(row.get(YEAR_COL, "") or "YEAR"))
    title = safe_filename(str(row.get(TITLE_COL, "") or "TITLE"), max_len=120)
    url = str(row.get(URL_COL, "") or "")
    uid = sha1_short(url, 10)
    fname = f"{venue}_{year}_{uid}_{title}.pdf"
    return os.path.join(PDF_DIR, fname)


def load_log_index() -> Dict[str, dict]:
    idx: Dict[str, dict] = {}
    if not os.path.exists(LOG_JSONL):
        return idx

    with open(LOG_JSONL, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                u = obj.get("URL")
                if u:
                    idx[u] = obj
            except json.JSONDecodeError:
                continue
    return idx


def append_log(obj: dict) -> None:
    log_dir = os.path.dirname(LOG_JSONL)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)
    with open(LOG_JSONL, "a", encoding="utf-8") as f:
        f.write(json.dumps(obj, ensure_ascii=False) + "\n")


def is_excluded_by_llm_decision(x) -> bool:
    return norm(str(x)).lower() == "exclude"


JUDGE2_SYSTEM_PROMPT = """
You are a strict meta-review judge for HCI / NLP / AI user-study screening.

Your job is to decide whether a paper reports a REAL human–LLM interaction study.

Definition of REAL human–LLM interaction:
A study counts as include only if human participants directly interact with an LLM system during the study.
This means the participant is in an active interaction loop with the LLM system, such as:
- chatting with the LLM
- prompting the LLM
- iteratively refining requests and receiving responses
- using an interface/tool that queries an LLM live during the study
- collaborating with, consulting, or being assisted by an LLM system in-session

Critical exclusion:
DO NOT count studies where humans only evaluate, annotate, label, rate, rank, compare, or review outputs that were generated by an LLM,
if the humans themselves are not directly interacting with the LLM system during the study.

Examples that should be EXCLUDE:
- participants rate LLM outputs
- crowdworkers judge which model output is better
- annotators label whether LLM answers are good/bad
- humans review summaries, essays, recommendations, or chatbot responses that were pre-generated
- benchmark creation where people only inspect model outputs
- expert evaluation of LLM-generated content without direct interaction

Also EXCLUDE:
- no human-subject study
- purely algorithmic/system paper
- simulation only
- participants interact with a non-LLM system and the LLM is only in the backend with no meaningful participant-model interaction described
- the paper discusses possible use but does not report an actual interactive user study

Use UNKNOWN only when the PDF does not provide enough evidence to determine the study setup.

Decision labels:
- include
- exclude
- unknown

Return ONLY valid JSON with exactly these keys:
{
  "decision": "include" | "exclude" | "unknown",
  "confidence": 0.0,
  "reason": "short explanation in 1-3 sentences"
}

Reason requirements:
- Be concrete and mention the interaction criterion.
- If excluded, explicitly say whether it is because participants only evaluated outputs, or because there was no actual human–LLM interaction study.
- Do not quote long passages.
- Do not include markdown.
"""


def judge_pdf_with_openai(client: OpenAI, pdf_path: str, paper_title: str, paper_url: str) -> Tuple[str, float, str]:
    with open(pdf_path, "rb") as f:
        uploaded = client.files.create(file=f, purpose="assistants")

    schema = {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "decision": {
                "type": "string",
                "enum": ["include", "exclude", "unknown"]
            },
            "confidence": {
                "type": "number"
            },
            "reason": {
                "type": "string"
            }
        },
        "required": ["decision", "confidence", "reason"]
    }

    resp = client.responses.create(
        model=MODEL,
        max_output_tokens=MAX_OUTPUT_TOKENS,
        text={
            "format": {
                "type": "json_schema",
                "name": "judge2_result",
                "schema": schema,
                "strict": True
            }
        },
        input=[
            {
                "role": "system",
                "content": [
                    {"type": "input_text", "text": JUDGE2_SYSTEM_PROMPT}
                ],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_text",
                        "text": (
                            f"Paper title: {paper_title}\n"
                            f"Paper URL: {paper_url}\n\n"
                            "Read the PDF carefully and decide whether this paper contains a real human–LLM interaction study "
                            "under the definition above. Focus especially on the method / study / experiment sections."
                        )
                    },
                    {
                        "type": "input_file",
                        "file_id": uploaded.id
                    }
                ],
            },
        ],
    )

    out_text = getattr(resp, "output_text", None)
    if not out_text:
        out_text = str(resp)

    text = out_text.strip()
    text = re.sub(r"^```(?:json)?\s*|\s*```$", "", text, flags=re.I | re.M).strip()

    try:
        obj = json.loads(text)
    except Exception:
        m = re.search(r"\{.*\}", text, flags=re.S)
        if not m:
            return "unknown", 0.0, "Model output was not valid JSON."
        try:
            obj = json.loads(m.group(0))
        except Exception:
            return "unknown", 0.0, "Model output was not valid JSON."

    decision = norm(obj.get("decision", "unknown")).lower()
    if decision not in {"include", "exclude", "unknown"}:
        decision = "unknown"

    try:
        conf = float(obj.get("confidence", 0.0))
    except Exception:
        conf = 0.0
    conf = max(0.0, min(1.0, conf))

    reason = norm(obj.get("reason", ""))
    if not reason:
        reason = "No reason returned by model."

    return decision, conf, reason


def main():
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("Missing OPENAI_API_KEY environment variable.")

    os.makedirs(os.path.dirname(OUTPUT_CSV), exist_ok=True)

    df = pd.read_csv(INPUT_CSV)

    for c in ["Judge2_include", "Judge2_confidence", "Judge2_reason"]:
        if c not in df.columns:
            df[c] = ""

    log_idx = load_log_index()
    client = OpenAI(api_key=api_key)

    processed = 0

    for i, row in tqdm(df.iterrows(), total=len(df), desc="Judge2", unit="paper"):
        rowd = row.to_dict()
        url = norm(str(rowd.get(URL_COL, "")))

        # Only process lines where LLM_Decision is NOT exclude
        if DECISION_COL in df.columns and is_excluded_by_llm_decision(rowd.get(DECISION_COL, "")):
            continue

        if not url:
            df.at[i, "Judge2_include"] = "unknown"
            df.at[i, "Judge2_confidence"] = 0.0
            df.at[i, "Judge2_reason"] = "Missing URL."
            continue

        if url in log_idx:
            prev = log_idx[url]
            df.at[i, "Judge2_include"] = prev.get("Judge2_include", "unknown")
            df.at[i, "Judge2_confidence"] = prev.get("Judge2_confidence", 0.0)
            df.at[i, "Judge2_reason"] = prev.get("Judge2_reason", "")
            continue

        pdf_path = build_expected_pdf_path(rowd)

        if not (os.path.exists(pdf_path) and os.path.getsize(pdf_path) > 0):
            reason = f"PDF missing, skipped: {os.path.basename(pdf_path)}"
            df.at[i, "Judge2_include"] = "unknown"
            df.at[i, "Judge2_confidence"] = 0.0
            df.at[i, "Judge2_reason"] = reason

            rec = {
                "URL": url,
                "Judge2_include": "unknown",
                "Judge2_confidence": 0.0,
                "Judge2_reason": reason,
                "timestamp": time.time(),
            }
            append_log(rec)
            log_idx[url] = rec
            continue

        title = str(rowd.get(TITLE_COL, "") or "")

        try:
            decision, conf, reason = judge_pdf_with_openai(client, pdf_path, title, url)
        except Exception as e:
            decision, conf, reason = "unknown", 0.0, f"API/error: {type(e).__name__}: {e}"

        df.at[i, "Judge2_include"] = decision
        df.at[i, "Judge2_confidence"] = conf
        df.at[i, "Judge2_reason"] = reason

        rec = {
            "URL": url,
            "Judge2_include": decision,
            "Judge2_confidence": conf,
            "Judge2_reason": reason,
            "pdf_file": os.path.basename(pdf_path),
            "timestamp": time.time(),
        }
        append_log(rec)
        log_idx[url] = rec

        processed += 1
        if processed % SAVE_EVERY == 0:
            df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
    print(f"[done] wrote {OUTPUT_CSV} and log {LOG_JSONL}")


if __name__ == "__main__":
    main()